### ISSUE TITLE
提个可能有点奇怪的需求，稿件名称重复

### ISSUE THREAD

**Issue by verity886** [Left024/BiliFavoritesDownloader#2]
有少数up主的投稿，不同稿件但稿件名称完全相同，导致脚本检测到同样名称不执行下载。[例子](https://space.bilibili.com/510904807/video)
手动删除date和title文件后，下载也会覆盖原来的同样名字的旧稿件
看能不能通过bv号来验证稿件是否相同，然后下载目录给稿件文件夹加上时间戳防止被覆盖

**Comment by Left024** [comment]
已支持
